### ISSUE TITLE
Props Question

### ISSUE THREAD

**Issue by chrisgitrepo** [laurenskling/keystone-with-react-engine#1]
Hi Laurens,

I just wanted to say thank you for putting this repo up, I've found it very useful. I hate using Jade Templates, so react-engine is also where I am going. 

Im just trying to understand.. how does props actually get passed to the jsx files so that values from props.user & props.title etc. can be used? I want to pass my own values from the server in the future in the same way you do this with Keystone.

Thank you,

Chris

**Comment by laurenskling** [comment]
Hello Chris, 
thanks for your message.

React-Engine takes `res.locals` and inserts them as `props` on the rendered template. From here you can pass them down to `<Default />` or wherever you needs the props.

So values end up in your template just as it did in jade
