### ISSUE TITLE
cookie secret

### ISSUE THREAD

**Issue by sebolek** [laurenskling/keystone-with-react-engine#3]
I keep getting this error when trying npm start:

KeystoneJS Configuration Error:

Please provide a `cookie secret` value for session encryption.

error Command failed with exit code 1.

Where do I set the 'cookie secret'?

**Comment by laurenskling** [comment]
It's a part of what keystone needs from your `.env` file. There is no `.env` file included in this package.

http://keystonejs.com/docs/configuration/#options-database
